import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Invoice } from "../types/invoice";

export const exportInvoicePDF = (invoice: Invoice) => {
    const doc = new jsPDF();

    doc.setFontSize(16);
    doc.text("TAX INVOICE", 14, 20);

    doc.setFontSize(12);
    doc.text("VK Tax & Law Chamber®", 14, 30);
    doc.text("Email: vkcalc.in@gmail.com", 14, 36);
    doc.text("Phone: +91-7018064385", 14, 42);

    doc.text(`Invoice No: ${invoice.invoice_number}`, 14, 55);
    doc.text(
        `Date: ${new Date(invoice.created_at || "").toLocaleDateString()}`,
        14,
        62
    );

    doc.text(`Client: ${invoice.client_name}`, 14, 70);
    if (invoice.client_gstin) {
        doc.text(`GSTIN: ${invoice.client_gstin}`, 14, 77);
    }

    autoTable(doc, {
        startY: 85,
        head: [["Description", "Amount (₹)"]],
        body: [
            [`Subscription Plan (${invoice.plan})`, invoice.amount.toFixed(2)],
            [`GST (${invoice.gst_rate}%)`, invoice.gst_amount.toFixed(2)],
            ["Total", invoice.total_amount.toFixed(2)],
        ],
    });

    doc.text(
        "Generated by SUITCASE – Court Fee & Case Manager Suite",
        14,
        doc.internal.pageSize.height - 20
    );

    doc.save(`${invoice.invoice_number}.pdf`);
};
