import PDFDocument from "pdfkit";

export const generate65BCertificate = ({
    user_name,
    certInfo,
    hash,
    txHash,
}: any) => {
    const doc = new PDFDocument();

    const buffers: Buffer[] = [];
    doc.on("data", buffers.push.bind(buffers));

    return new Promise<Buffer>((resolve) => {
        doc.on("end", () => resolve(Buffer.concat(buffers)));

        doc.fontSize(14).text("CERTIFICATE UNDER SECTION 65B", {
            align: "center",
        });

        doc.moveDown();

        doc.fontSize(11);

        doc.text(`I, ${user_name}, do hereby certify that:`);

        doc.moveDown();

        doc.text(
            "1. The accompanying electronic record (Audit Report PDF) was generated by a computer system in the ordinary course of activities."
        );

        doc.text(
            "2. The computer system was functioning properly and the information is regularly stored and processed."
        );

        doc.text(
            `3. The document integrity is ensured by SHA-256 hash: ${hash}`
        );

        doc.text(
            `4. The document has been digitally signed using a valid Digital Signature Certificate issued by ${certInfo.issuerCN}.`
        );

        doc.text(
            `5. Certificate Holder (CN): ${certInfo.subjectCN}`
        );

        doc.text(
            `6. Certificate Validity: ${new Date(
                certInfo.validFrom
            ).toLocaleDateString()} to ${new Date(
                certInfo.validTo
            ).toLocaleDateString()}`
        );

        if (txHash) {
            doc.text(
                `7. The document hash has been anchored on blockchain. Transaction ID: ${txHash}`
            );
        }

        doc.moveDown();

        doc.text(
            "I declare that the above information is true and correct to the best of my knowledge and belief."
        );

        doc.moveDown(2);

        doc.text(`Date: ${new Date().toLocaleDateString()}`);
        doc.text(`Place: __________`);

        doc.moveDown(2);

        doc.text(`Digitally Signed By: ${user_name}`);

        doc.end();
    });
};