import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import QRCode from "qrcode";
import { supabase } from "../config/supabase.js";
import { generateSignature } from "./signature.js";

export const generateAuditPDF = async (document_id: string) => {
    const filePath = path.join(__dirname, `../../tmp/audit-${document_id}.pdf`);

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(fs.createWriteStream(filePath));

    // =========================
    // FETCH DATA
    // =========================
    const { data: logs } = await supabase
        .from("document_access_logs")
        .select("*")
        .eq("document_id", document_id)
        .order("created_at", { ascending: true });

    // 🔹 Fetch organization details
    const { data: org } = await supabase
        .from("organizations")
        .select("*")
        .eq("id", logs?.[0]?.organization_id)
        .single();

    // =========================
    // QR CODE
    // =========================
    const verifyUrl = `${process.env.FRONTEND_URL}/verify/${document_id}`;
    const qrImage = await QRCode.toDataURL(verifyUrl);

    // =========================
    // HEADER (CHAMBER BRANDING)
    // =========================
    if (org?.logo_url) {
        doc.image(org.logo_url, 50, 45, { width: 50 });
    }
    doc
        .fontSize(16)
        .text(org?.name || "ORGANIZATION NAME", { align: "center" });

    doc
        .fontSize(10)
        .text(
            `${org?.address || ""} | ${org?.contact || ""} | ${org?.email || ""}`,
            { align: "center" }
        );

    doc
        .fontSize(10)
        .text("Address Line | Contact | Email", { align: "center" });

    doc.moveDown();

    doc
        .fontSize(14)
        .text("DOCUMENT AUDIT REPORT", { align: "center", underline: true });

    doc.moveDown();

    // =========================
    // DOCUMENT DETAILS
    // =========================
    doc.fontSize(10).text(`Document ID: ${document_id}`);
    doc.text(`Generated At: ${new Date().toLocaleString()}`);

    doc.moveDown();

    // =========================
    // GST / LEGAL BLOCK
    // =========================
    doc.moveDown();

    doc.fontSize(11).text("Reference Details:", { underline: true });

    doc.fontSize(9).text(`Organization: ${org?.name}`);
    doc.text(`Place of Supply: ${org?.state || "Himachal Pradesh"}`);
    doc.text(`Jurisdiction: ${org?.jurisdiction || "Local Court"}`);
    doc.text(`Report Type: Audit Evidence`);
    doc.text(`Generated By: System`);

    // =========================
    // AUDIT TABLE
    // =========================
    doc.fontSize(12).text("Audit Trail:", { underline: true });
    doc.moveDown(0.5);

    logs?.forEach((log, i) => {
        doc
            .fontSize(9)
            .text(
                `${i + 1}. ${log.access_type} | User: ${log.user_id || "Client"
                } | IP: ${log.ip_address}`
            );

        doc.text(`Time: ${new Date(log.created_at).toLocaleString()}`);
        doc.text(`Hash: ${log.hash}`);
        doc.moveDown();
    });

    // =========================
    // DIGITAL SIGNATURE
    // =========================
    const signature = generateSignature(logs);

    doc.moveDown();
    doc.text("Digital Signature:", { underline: true });
    doc.fontSize(8).text(signature);

    // =========================
    // QR CODE
    // =========================
    doc.moveDown();
    doc.text("Scan to Verify:", { align: "center" });

    doc.image(qrImage, {
        fit: [100, 100],
        align: "center",
    });

    // =========================
    // DECLARATION (LEGAL TEXT)
    // =========================
    doc.moveDown();
    doc
        .fontSize(9)
        .text(
            "This report is system-generated from immutable, hash-linked audit logs. Any tampering invalidates the integrity of this document.",
            { align: "justify" }
        );

    // =========================
    // SIGNATURE + SEAL
    // =========================
    doc.moveDown(2);

    doc.text("Authorized Signatory:");
    doc.text("_________________________");

    doc.moveDown();

    doc.text("Official Seal:");
    doc.text("[AFFIX CHAMBER SEAL]");

    doc.end();

    return filePath;
};